name: cloudflare-ddns
services:
  cloudflare-ddns:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 15891M
    environment:
      - CF_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # add access token, see guide here https://developers.cloudflare.com/fundamentals/api/get-started/create-token/
      - DOMAINS=deleven.net, *.deleven.net
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGID=1000
      - PROXIED=false
      - PUID=1000
    image: favonia/cloudflare-ddns:latest
    labels:
      icon: https://yt3.googleusercontent.com/lyrJ4UAHQLNGpkLQbL03Xh6GJvAZxA1loSDBRYPWuRbssAoEdCsN0DeybqdKNiJH7KA9NsoH-w=s900-c-k-c0x00ffffff-no-rj
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: CF_API_TOKEN
          description:
            en_us: ""
        - container: DOMAINS
          description:
            en_us: ""
        - container: PROXIED
          description:
            en_us: ""
        - container: PATH
          description:
            en_us: ""
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: unknown
  description:
    en_us: ""
  developer: unknown
  hostname: ""
  icon: https://yt3.googleusercontent.com/lyrJ4UAHQLNGpkLQbL03Xh6GJvAZxA1loSDBRYPWuRbssAoEdCsN0DeybqdKNiJH7KA9NsoH-w=s900-c-k-c0x00ffffff-no-rj
  index: /
  main: cloudflare-ddns
  port_map: ""
  scheme: http
  store_app_id: cloudflare-ddns
  tagline:
    en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  thumbnail: ""
  tips:
    custom: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  title:
    custom: ""
    en_us: cloudflare-ddns
