name: dreamy_leonardo
services:
  watchtower:
    cpu_shares: 90
    command: []
    container_name: watchtower
    deploy:
      resources:
        limits:
          memory: 15891M
    image: containrrr/watchtower
    labels:
      icon: https://github.com/containrrr/watchtower/raw/main/logo.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports: []
    devices: []
    cap_add: []
    environment: []
    network_mode: host
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://github.com/containrrr/watchtower/raw/main/logo.png
  index: /
  port_map: ""
  scheme: http
  store_app_id: dreamy_leonardo
  title:
    custom: watchtower
