name: gallant_angelina
services:
  yacht:
    cpu_shares: 90
    command: []
    container_name: yacht
    deploy:
      resources:
        limits:
          memory: 15891M
    image: selfhostedpro/yacht
    labels:
      icon: https://yacht.sh/img/logo-light.svg
    ports:
      - target: 8000
        published: "8001"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Yacht/config
        target: /config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: 192.168.1.108
  icon: https://yacht.sh/img/logo-light.svg
  index: /
  port_map: "8001"
  scheme: http
  store_app_id: gallant_angelina
  title:
    custom: Yacht
