version: "3"
services:
  cloudflare-ddns-updater:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    cap_add:
      - SETUID # Leave this alone, as is
      - SETGID # Leave this alone, as is
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${Ubuntu_PUID}
      - PGID=${Ubuntu_PUID}
      - CF_API_TOKEN=${CDDNSU_CF_API_TOKEN}
      - DOMAINS=${CDDNSU_DOMAINS}
      - PROXIED=true
      - IP6_PROVIDER=none
    restart: unless-stopped
networks: {}