version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
x-dockge:
  urls:
    - https://containrrr.dev/watchtower/
networks: {}
