name: Embed docker-compose.yml in README

permissions:
  contents: write

on:
  push:
    paths:
      - '**/README.md'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Code Embedder
        uses: kvankova/code-embedder@v1.1.2

      - name: Check if there are changes
        id: git_status
        run: |
          git add .
          if git diff-index --quiet HEAD; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.no_changes == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -m "Update embedded code"
          git push
